{% set name = "scitacean" %}
{% set version = "24.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scitacean-{{ version }}.tar.gz
  sha256: 09ba4d1a813c7dc7b9c84c941ab30cdcad7c449905eadc18ace2aaba8f9a1441

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - email-validator
    - paramiko
    - pydantic >=2
    - python-dateutil
    - requests >=2.31

test:
  imports:
    - scitacean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/scitacean/
  summary: High-level interface for SciCat
  dev_url: https://github.com/SciCatProject/scitacean
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jl-wynen
    - nitrosx
