{% set name = "scitacean" %}
{% set version = "23.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scitacean-{{ version }}.tar.gz
  sha256: b0299fdd3df5b62d680713003dba4cbae5ac6c24251370937a5dcd7d00ecf50f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - email-validator
    - fabric
    - pydantic
    - python-dateutil
    - requests

test:
  imports:
    - scitacean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/scitacean/
  summary: High-level interface for SciCat
  dev_url: https://github.com/SciCatProject/scitacean
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jl-wynen
    - nitrosx
