{% set name = "scitacean" %}
{% set version = "24.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scitacean-{{ version }}.tar.gz
  sha256: 924c788279125285b9da9703a8a19f107e54588340cf71c6bb21ea3f1c71b971

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - email-validator >=2
    - httpx >=0.24
    - paramiko >=3
    - pydantic >=2
    - python-dateutil >=2.8

test:
  imports:
    - scitacean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/scitacean/
  summary: High-level interface for SciCat
  dev_url: https://github.com/SciCatProject/scitacean
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jl-wynen
    - nitrosx
