{% set name = "scitacean" %}
{% set version = "25.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scitacean-{{ version }}.tar.gz
  sha256: 69d64d68f5be5e6af01ee06a55b018e69865ae7538bf233ba483e92610497260

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=68
    - setuptools-scm >=8.0
  run:
    - python >={{ python_min }}
    - email-validator >=2
    - httpx >=0.24
    - paramiko >=3
    - pydantic >=2
    - python-dateutil >=2.8

test:
  imports:
    - scitacean
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/scitacean/
  summary: High-level interface for SciCat
  dev_url: https://github.com/SciCatProject/scitacean
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jl-wynen
    - nitrosx
