{% set name = "scitacean" %}
{% set version = "24.12.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scitacean-{{ version }}.tar.gz
  sha256: 33ed6e91325d7e79760d427c0de5bd736987404bd1a9f7c65b3ed30aa51b2832

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=68
  run:
    - python >={{ python_min }}
    - email-validator >=2
    - httpx >=0.24
    - paramiko >=3
    - pydantic >=2
    - python-dateutil >=2.8

test:
  imports:
    - scitacean
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/scitacean/
  summary: High-level interface for SciCat
  dev_url: https://github.com/SciCatProject/scitacean
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jl-wynen
    - nitrosx
