{% set name = "scitacean" %}
{% set version = "23.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scitacean-{{ version }}.tar.gz
  sha256: f2af81ef9ddc664a1144d1df1bdb9e1c4af77af61dc5299dbf2b8b697d21f7cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - email-validator
    - fabric
    - filelock
    - paramiko
    - pydantic
    - python-dateutil
    - requests

test:
  imports:
    - scitacean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/scitacean/
  summary: High-level interface for SciCat
  dev_url: https://github.com/SciCatProject/scitacean
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jl-wynen
    - nitrosx
