context:
  name: scitacean
  version: "25.3.2"
  python_min: "3.10"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/scitacean-${{ version }}.tar.gz
  sha256: 94bb5538c250e6ae56aac130576f26b963691f2168fcdcbbd9f2fe916129c2e6

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=68
    - setuptools-scm >=8.0
  run:
    - python >=${{ python_min }}
    - email-validator >=2
    - httpx >=0.24
    - paramiko >=3
    - pydantic >=2
    - python-dateutil >=2.8
    - tomli >=2.2.0

tests:
  - python:
      imports:
        - scitacean
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://pypi.org/project/scitacean/
  summary: High-level interface for SciCat
  repository: https://github.com/SciCatProject/scitacean
  documentation: https://scicatproject.github.io/scitacean/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jl-wynen
    - nitrosx
